### ISSUE TITLE
anope on centos 8 fails to start

### ISSUE THREAD

**Issue by daniel-Jones** [Natolumin/rpms#2]
```
May 23 15:30:08 danieljon.es systemd[1]: anope.service: Can't open PID file /run/anope/services.pid (yet?) after start: No such file or directory
May 23 15:31:36 danieljon.es systemd[1]: anope.service: Start operation timed out. Terminating.
May 23 15:31:36 danieljon.es systemd[1]: anope.service: Failed with result 'timeout'.
May 23 15:31:36 danieljon.es systemd[1]: Failed to start IRC Services Daemon.
```
prior to stopping itself, anope connects as expected.

**Comment by daniel-Jones** [comment]
~i'm not sure if anope not creating that pid file might cause the timeout. I have my pidfile set at another location in my config. this might not be the correct thing to do, however it cannot write into /run/anope~
seems like a runtime directory should be made that anope can write into, but i'm really not sure

**Comment by daniel-Jones** [comment]
seems setting the pid to '/var/run/anope/services.pid' in anopes config correctly creates the file. i was under the impression it wouldn't because of permissions, i was wrong.

apologies

**Comment by Natolumin** [comment]
anope.service has 
```systemd
RuntimeDirectory=anope
```
which should create a `/run/anope` directory and allow anope to write to it; Since this package doesn't ship a default configuration (which I guess is something I should fix) you'll need to set the pid location explicitly to `/run/anope/services.pid`
